title: АНО «ФАКТОРИАЛ»
description: Культурно-научные и образовательные проекты
baseurl: ""
url: "https://factorial.spb.ru"
markdown: kramdown
excerpt_separator: "<!--more-->"

news_count: 5

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /news/:slug/
